version: "3.8"

services:
  db:
    image: "postgres:15.3-bookworm"
    env_file:
      - .env
    ports:
      - "${PGPORT}:${PGPORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 3
    volumes:
      - ./data:/var/lib/postgresql/data
    profiles:
      - "dev"
      - "prod"
      - "ingestion"

  db-testing:
    image: "postgres:15.3-bookworm"
    env_file:
      - .env.testing
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 3
    profiles:
      - "testing"

  backend-dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./patches:/usr/local/app/patches
      - ./src:/usr/local/app/src
      - ./tsconfig.json:/usr/local/app/tsconfig.json
    ports:
      - "${PORT}:${PORT}"
    profiles:
      - "dev"

  backend-prod:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    profiles:
      - "prod"

  ingestion:
    command: ["pnpm", "ts-node", "src/ingest.ts"]
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./patches:/usr/local/app/patches
      - ./src:/usr/local/app/src
      - ./tsconfig.json:/usr/local/app/tsconfig.json
    profiles:
      - "ingestion"

  backend-testing:
    command: ["pnpm", "jest", "--runInBand", "--verbose"]
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env.testing
    depends_on:
      db-testing:
        condition: service_healthy
    volumes:
      - ./patches:/usr/local/app/patches
      - ./src:/usr/local/app/src
      - ./tsconfig.json:/usr/local/app/tsconfig.json
      - ./jest.config.js:/usr/local/app/jest.config.js
    tty: true
    profiles:
      - "testing"
