version: "3.8"

services:
  db:
    image: "postgres:15.3-bookworm"
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 3

  backend-dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./patches:/usr/local/app/patches
      - ./src:/usr/local/app/src
      - ./package.json:/usr/local/app/package.json
      - ./tsconfig.json:/usr/local/app/tsconfig.json
      - ./pnpm-lock.yaml:/usr/local/app/pnpm-lock.yaml
    ports:
      - "${PORT}:${PORT}"

  backend-prod:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    profiles:
      - "prod"

  ingestion:
    command: ["dumb-init", "node", "build/ingest.js"]
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - "ingestion"
