version: '3'

services:
  db: # If you change this here, remember to change it in .env and .env.example as well
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    env_file:
      - .env
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
