name: Host a new release of ChronoFactorem

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  release:
    name: Build and deploy to prod
    runs-on: self-hosted
    steps:
      - name: ssh into machine, and clone repo
        run: |
            cd /home/ubuntu/clones
            cd chronofactorem-rewrite-prod
            git pull
            docker compose --profile ingestion down
            docker compose --profile prod down
            docker compose --profile prod up --build -d
